export const orderBook = {
  ADD_SELL: 'ADD_SELL',
  ADD_BUY: 'ADD_BUY',
  UPDATE_SELL: 'UPDATE_SELL',
  UPDATE_BUY: 'UPDATE_BUY',
  REMOVE_SELL: 'REMOVE_SELL',
  REMOVE_BUY: 'REMOVE_BUY',
  RESET_SELL: 'RESET_SELL',
  RESET_BUY: 'RESET_BUY',
};
