export const status = {
  WAITING_FOR_EXCHANGE_RESPONSE: 'WAITING_FOR_EXCHANGE_RESPONSE',
  EXCHANGE_RESPONDED: 'EXCHANGE_RESPONDED',
  EXCHANGE_RESPONDED_WITH_ERROR: 'EXCHANGE_RESPONDED_WITH_ERROR',
};
